openapi: 3.1.0
info:
  version: 1.0.0
  title: Node.js Contacts API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    A REST API for managing contacts with authentication, email notifications, and image uploads.
    Features include user registration/login, contact CRUD operations, password reset via email,
    and photo uploads to Cloudinary.
tags:
  - name: Authentication
    description: User authentication endpoints
  - name: Contacts
    description: Contact management endpoints
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-hw6-tgzj.onrender.com
paths:
  /contacts:
    $ref: '../swagger/paths/contacts/get.yaml'
    $ref: '../swagger/paths/contacts/post.yaml'
  /contacts/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: Contact ID
        schema:
          type: string
    $ref: '../swagger/paths/contacts/{id}/get.yaml'
    $ref: '../swagger/paths/contacts/{id}/patch.yaml'
    $ref: '../swagger/paths/contacts/{id}/delete.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
